using System;


namespace AdifProperties
{
    public class ADIFProperties
    {
        public class AdifFieldObjects
        {
            public string ADDRESS { get; set; }
            public string ADDRESS_INTL { get; set; }
            public string AGE { get; set; }
            public string A_INDEX { get; set; }
            public string ANT_AZ { get; set; }
            public string ANT_EL { get; set; }
            public string ANT_PATH { get; set; }
            public string ARRL_SECT { get; set; }
            public string AWARD_SUBMITTED { get; set; }
            public string AWARD_GRANTED { get; set; }
            public string BAND { get; set; }
            public string BAND_RX { get; set; }
            public string CALL { get; set; }
            public string CHECK { get; set; }
            public string CLASS { get; set; }
            public string CLUBLOG_QSO_UPLOAD_DATE { get; set; }
            public string CLUBLOG_QSO_UPLOAD_STATUS { get; set; }
            public string CNTY { get; set; }
            public string COMMENT { get; set; }
            public string COMMENT_INTL { get; set; }
            public string CONT { get; set; }
            public string CONTACTED_OP { get; set; }
            public string CONTEST_ID { get; set; }
            public string COUNTRY { get; set; }
            public string COUNTRY_INTL { get; set; }
            public string CQZ { get; set; }
            public string CREDIT_SUBMITTED { get; set; }
            public string CREDIT_GRANTED { get; set; }
            public string DARC_DOK { get; set; }
            public string DISTANCE { get; set; }
            public string DXCC { get; set; }
            public string EMAIL { get; set; }
            public string EQ_CALL { get; set; }
            public string EQSL_QSLRDATE { get; set; }
            public string EQSL_QSLSDATE { get; set; }
            public string EQSL_QSL_RCVD { get; set; }
            public string EQSL_QSL_SENT { get; set; }
            public string FISTS { get; set; }
            public string FISTS_CC { get; set; }
            public string FORCE_INIT { get; set; }
            public string FREQ { get; set; }
            public string FREQ_RX { get; set; }
            public string GRIDSQUARE { get; set; }
            public string GUEST_OP { get; set; }
            public string HRDLOG_QSO_UPLOAD_DATE { get; set; }
            public string HRDLOG_QSO_UPLOAD_STATUS { get; set; }
            public string IOTA { get; set; }
            public string IOTA_ISLAND_ID { get; set; }
            public string ITUZ { get; set; }
            public string K_INDEX { get; set; }
            public string LAT { get; set; }
            public string LON { get; set; }
            public string LOTW_QSLRDATE { get; set; }
            public string LOTW_QSLSDATE { get; set; }
            public string LOTW_QSL_RCVD { get; set; }
            public string LOTW_QSL_SENT { get; set; }
            public string MAX_BURSTS { get; set; }
            public string MODE { get; set; }
            public string MS_SHOWER { get; set; }
            public string MY_ANTENNA { get; set; }
            public string MY_ANTENNA_INTL { get; set; }
            public string MY_CITY { get; set; }
            public string MY_CITY_INTL { get; set; }
            public string MY_CNTY { get; set; }
            public string MY_COUNTRY { get; set; }
            public string MY_COUNTRY_INTL { get; set; }
            public string MY_CQ_ZONE { get; set; }
            public string MY_DXCC { get; set; }
            public string MY_FISTS { get; set; }
            public string MY_GRIDSQUARE { get; set; }
            public string MY_IOTA { get; set; }
            public string MY_IOTA_ISLAND_ID { get; set; }
            public string MY_ITU_ZONE { get; set; }
            public string MY_LAT { get; set; }
            public string MY_LON { get; set; }
            public string MY_NAME { get; set; }
            public string MY_NAME_INTL { get; set; }
            public string MY_POSTAL_CODE { get; set; }
            public string MY_POSTAL_CODE_INTL { get; set; }
            public string MY_RIG { get; set; }
            public string MY_RIG_INTL { get; set; }
            public string MY_SIG { get; set; }
            public string MY_SIG_INTL { get; set; }
            public string MY_SIG_INFO { get; set; }
            public string MY_SIG_INFO_INTL { get; set; }
            public string MY_SOTA_REF { get; set; }
            public string MY_STATE { get; set; }
            public string MY_STREET { get; set; }
            public string MY_STREET_INTL { get; set; }
            public string MY_USACA_COUNTIES { get; set; }
            public string MY_VUCC_GRIDS { get; set; }
            public string NAME { get; set; }
            public string NAME_INTL { get; set; }
            public string NOTES { get; set; }
            public string NOTES_INTL { get; set; }
            public string NR_BURSTS { get; set; }
            public string NR_PINGS { get; set; }
            public string OPERATOR { get; set; }
            public string OWNER_CALLSIGN { get; set; }
            public string PFX { get; set; }
            public string PRECEDENCE { get; set; }
            public string PROP_MODE { get; set; }
            public string PUBLIC_KEY { get; set; }
            public string QRZCOM_QSO_UPLOAD_DATE { get; set; }
            public string QRZCOM_QSO_UPLOAD_STATUS { get; set; }
            public string QSLMSG { get; set; }
            public string QSLMSG_INTL { get; set; }
            public string QSLRDATE { get; set; }
            public string QSLSDATE { get; set; }
            public string QSL_RCVD { get; set; }
            public string QSL_RCVD_VIA { get; set; }
            public string QSL_SENT { get; set; }
            public string QSL_SENT_VIA { get; set; }
            public string QSL_VIA { get; set; }
            public string QSO_COMPLETE { get; set; }
            public string QSO_DATE { get; set; }
            public string QSO_DATE_OFF { get; set; }
            public string QSO_RANDOM { get; set; }
            public string QTH { get; set; }
            public string QTH_INTL { get; set; }
            public string REGION { get; set; }
            public string RIG { get; set; }
            public string RIG_INTL { get; set; }
            public string RST_RCVD { get; set; }
            public string RST_SENT { get; set; }
            public string RX_PWR { get; set; }
            public string SAT_MODE { get; set; }
            public string SAT_NAME { get; set; }
            public string SFI { get; set; }
            public string SIG { get; set; }
            public string SIG_INTL { get; set; }
            public string SIG_INFO { get; set; }
            public string SIG_INFO_INTL { get; set; }
            public string SILENT_KEY { get; set; }
            public string SKCC { get; set; }
            public string SOTA_REF { get; set; }
            public string SRX { get; set; }
            public string SRX_STRING { get; set; }
            public string STATE { get; set; }
            public string STATION_CALLSIGN { get; set; }
            public string STX { get; set; }
            public string STX_STRING { get; set; }
            public string SUBMODE { get; set; }
            public string SWL { get; set; }
            public string TEN_TEN { get; set; }
            public string TIME_OFF { get; set; }
            public string TIME_ON { get; set; }
            public string TX_PWR { get; set; }
            public string UKSMG { get; set; }
            public string USACA_COUNTIES { get; set; }
            public string VE_PROV { get; set; }
            public string VUCC_GRIDS { get; set; }
            public string WEB { get; set; }
            //  N1MM
            public string APP_N1MM_POINTS { get; set; }
            public string APP_N1MM_RADIO_NR { get; set; }
            public string APP_N1MM_CONTINENT { get; set; }
            public string APP_N1MM_RUN1RUN2 { get; set; }
            public string APP_N1MM_RADIOINTERFACED { get; set; }
            public string APP_N1MM_ISORIGINAL { get; set; }
            public string APP_N1MM_NETBIOSNAME { get; set; }
            public string APP_N1MM_ISRUNQSO { get; set; }
            public string APP_N1MM_ID { get; set; }
            public string APP_N1MM_CLAIMEDQSO { get; set; }
            //eQSL.cc
            public string APP_EQSL_AG { get; set; }
        }
    }
}
