//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.42000
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ADX {
    
    private ADXHEADER hEADERField;
    
    private ADXRECORD[] rECORDSField;
    
    /// <remarks/>
    public ADXHEADER HEADER {
        get {
            return this.hEADERField;
        }
        set {
            this.hEADERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("RECORD", IsNullable=false)]
    public ADXRECORD[] RECORDS {
        get {
            return this.rECORDSField;
        }
        set {
            this.rECORDSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ADXHEADER {
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ADIF_VER", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CREATED_TIMESTAMP", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PROGRAMID", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PROGRAMVERSION", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("USERDEF", typeof(ADXUSERDEF))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ADXUSERDEF {
    
    private uint fIELDIDField;
    
    private string tYPEField;
    
    private string eNUMField;
    
    private string rANGEField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint FIELDID {
        get {
            return this.fIELDIDField;
        }
        set {
            this.fIELDIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ENUM {
        get {
            return this.eNUMField;
        }
        set {
            this.eNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RANGE {
        get {
            return this.rANGEField;
        }
        set {
            this.rANGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    ADIF_VER,
    
    /// <remarks/>
    CREATED_TIMESTAMP,
    
    /// <remarks/>
    PROGRAMID,
    
    /// <remarks/>
    PROGRAMVERSION,
    
    /// <remarks/>
    USERDEF,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ADXRECORD {
    
    private object[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    private string[] textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ADDRESS", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("ADDRESS_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("AGE", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("ANT_AZ", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("ANT_EL", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("ANT_PATH", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("APP", typeof(ADXRECORDAPP), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("ARRL_SECT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("AWARD_GRANTED", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("AWARD_SUBMITTED", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("A_INDEX", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("BAND", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("BAND_RX", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CALL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("CHECK", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("CLASS", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("CLUBLOG_QSO_UPLOAD_DATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CLUBLOG_QSO_UPLOAD_STATUS", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CNTY", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("COMMENT", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("COMMENT_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("CONT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CONTACTED_OP", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("CONTEST_ID", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("COUNTRY", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("COUNTRY_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("CQZ", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("CREDIT_GRANTED", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("CREDIT_SUBMITTED", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("DARC_DOK", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("DISTANCE", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("DXCC", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("EMAIL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("EQSL_QSLRDATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("EQSL_QSLSDATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("EQSL_QSL_RCVD", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("EQSL_QSL_SENT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("EQ_CALL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("FISTS", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("FISTS_CC", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("FORCE_INIT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("FREQ", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("FREQ_RX", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("GRIDSQUARE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("HRDLOG_QSO_UPLOAD_DATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("HRDLOG_QSO_UPLOAD_STATUS", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IOTA", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("IOTA_ISLAND_ID", typeof(System.Nullable<decimal>))]
    [System.Xml.Serialization.XmlElementAttribute("ITUZ", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("K_INDEX", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("LAT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("LON", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("LOTW_QSLRDATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("LOTW_QSLSDATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("LOTW_QSL_RCVD", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("LOTW_QSL_SENT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MAX_BURSTS", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("MODE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MS_SHOWER", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_ANTENNA", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_ANTENNA_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_CITY", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_CITY_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_CNTY", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_COUNTRY", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_COUNTRY_INTL", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_CQ_ZONE", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("MY_DXCC", typeof(uint))]
    [System.Xml.Serialization.XmlElementAttribute("MY_FISTS", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("MY_GRIDSQUARE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_IOTA", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_IOTA_ISLAND_ID", typeof(System.Nullable<decimal>))]
    [System.Xml.Serialization.XmlElementAttribute("MY_ITU_ZONE", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("MY_LAT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_LON", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_NAME", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_NAME_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_POSTAL_CODE", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_POSTAL_CODE_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_RIG", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_RIG_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_SIG", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_SIG_INFO", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_SIG_INFO_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_SIG_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_SOTA_REF", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_STATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("MY_STREET", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_STREET_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_USACA_COUNTIES", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("MY_VUCC_GRIDS", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("NAME", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("NAME_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("NOTES", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("NOTES_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("NR_BURSTS", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("NR_PINGS", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("OPERATOR", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("OWNER_CALLSIGN", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("PFX", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("PRECEDENCE", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("PROP_MODE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PUBLIC_KEY", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("QRZCOM_QSO_UPLOAD_DATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QRZCOM_QSO_UPLOAD_STATUS", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSLMSG", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("QSLMSG_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("QSLRDATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSLSDATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSL_RCVD", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSL_RCVD_VIA", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSL_SENT", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSL_SENT_VIA", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSL_VIA", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("QSO_COMPLETE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSO_DATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSO_DATE_OFF", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QSO_RANDOM", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("QTH", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("QTH_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("REGION", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("RIG", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("RIG_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("RST_RCVD", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("RST_SENT", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("RX_PWR", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("SAT_MODE", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SAT_NAME", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SFI", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("SIG", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SIG_INFO", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SIG_INFO_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SIG_INTL", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SILENT_KEY", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SKCC", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SOTA_REF", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SRX", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("SRX_STRING", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("STATE", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("STATION_CALLSIGN", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("STX", typeof(System.Nullable<decimal>))]
    [System.Xml.Serialization.XmlElementAttribute("STX_STRING", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SUBMODE", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("SWL", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("TEN_TEN", typeof(System.Nullable<decimal>))]
    [System.Xml.Serialization.XmlElementAttribute("TIME_OFF", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("TIME_ON", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("TX_PWR", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("UKSMG", typeof(decimal))]
    [System.Xml.Serialization.XmlElementAttribute("USACA_COUNTIES", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("USERDEF", typeof(ADXRECORDUSERDEF))]
    [System.Xml.Serialization.XmlElementAttribute("VUCC_GRIDS", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("WEB", typeof(string), IsNullable=true)]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ADXRECORDAPP {
    
    private string pROGRAMIDField;
    
    private string fIELDNAMEField;
    
    private string tYPEField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PROGRAMID {
        get {
            return this.pROGRAMIDField;
        }
        set {
            this.pROGRAMIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FIELDNAME {
        get {
            return this.fIELDNAMEField;
        }
        set {
            this.fIELDNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TYPE {
        get {
            return this.tYPEField;
        }
        set {
            this.tYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ADXRECORDUSERDEF {
    
    private string fIELDNAMEField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FIELDNAME {
        get {
            return this.fIELDNAMEField;
        }
        set {
            this.fIELDNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    ADDRESS,
    
    /// <remarks/>
    ADDRESS_INTL,
    
    /// <remarks/>
    AGE,
    
    /// <remarks/>
    ANT_AZ,
    
    /// <remarks/>
    ANT_EL,
    
    /// <remarks/>
    ANT_PATH,
    
    /// <remarks/>
    APP,
    
    /// <remarks/>
    ARRL_SECT,
    
    /// <remarks/>
    AWARD_GRANTED,
    
    /// <remarks/>
    AWARD_SUBMITTED,
    
    /// <remarks/>
    A_INDEX,
    
    /// <remarks/>
    BAND,
    
    /// <remarks/>
    BAND_RX,
    
    /// <remarks/>
    CALL,
    
    /// <remarks/>
    CHECK,
    
    /// <remarks/>
    CLASS,
    
    /// <remarks/>
    CLUBLOG_QSO_UPLOAD_DATE,
    
    /// <remarks/>
    CLUBLOG_QSO_UPLOAD_STATUS,
    
    /// <remarks/>
    CNTY,
    
    /// <remarks/>
    COMMENT,
    
    /// <remarks/>
    COMMENT_INTL,
    
    /// <remarks/>
    CONT,
    
    /// <remarks/>
    CONTACTED_OP,
    
    /// <remarks/>
    CONTEST_ID,
    
    /// <remarks/>
    COUNTRY,
    
    /// <remarks/>
    COUNTRY_INTL,
    
    /// <remarks/>
    CQZ,
    
    /// <remarks/>
    CREDIT_GRANTED,
    
    /// <remarks/>
    CREDIT_SUBMITTED,
    
    /// <remarks/>
    DARC_DOK,
    
    /// <remarks/>
    DISTANCE,
    
    /// <remarks/>
    DXCC,
    
    /// <remarks/>
    EMAIL,
    
    /// <remarks/>
    EQSL_QSLRDATE,
    
    /// <remarks/>
    EQSL_QSLSDATE,
    
    /// <remarks/>
    EQSL_QSL_RCVD,
    
    /// <remarks/>
    EQSL_QSL_SENT,
    
    /// <remarks/>
    EQ_CALL,
    
    /// <remarks/>
    FISTS,
    
    /// <remarks/>
    FISTS_CC,
    
    /// <remarks/>
    FORCE_INIT,
    
    /// <remarks/>
    FREQ,
    
    /// <remarks/>
    FREQ_RX,
    
    /// <remarks/>
    GRIDSQUARE,
    
    /// <remarks/>
    HRDLOG_QSO_UPLOAD_DATE,
    
    /// <remarks/>
    HRDLOG_QSO_UPLOAD_STATUS,
    
    /// <remarks/>
    IOTA,
    
    /// <remarks/>
    IOTA_ISLAND_ID,
    
    /// <remarks/>
    ITUZ,
    
    /// <remarks/>
    K_INDEX,
    
    /// <remarks/>
    LAT,
    
    /// <remarks/>
    LON,
    
    /// <remarks/>
    LOTW_QSLRDATE,
    
    /// <remarks/>
    LOTW_QSLSDATE,
    
    /// <remarks/>
    LOTW_QSL_RCVD,
    
    /// <remarks/>
    LOTW_QSL_SENT,
    
    /// <remarks/>
    MAX_BURSTS,
    
    /// <remarks/>
    MODE,
    
    /// <remarks/>
    MS_SHOWER,
    
    /// <remarks/>
    MY_ANTENNA,
    
    /// <remarks/>
    MY_ANTENNA_INTL,
    
    /// <remarks/>
    MY_CITY,
    
    /// <remarks/>
    MY_CITY_INTL,
    
    /// <remarks/>
    MY_CNTY,
    
    /// <remarks/>
    MY_COUNTRY,
    
    /// <remarks/>
    MY_COUNTRY_INTL,
    
    /// <remarks/>
    MY_CQ_ZONE,
    
    /// <remarks/>
    MY_DXCC,
    
    /// <remarks/>
    MY_FISTS,
    
    /// <remarks/>
    MY_GRIDSQUARE,
    
    /// <remarks/>
    MY_IOTA,
    
    /// <remarks/>
    MY_IOTA_ISLAND_ID,
    
    /// <remarks/>
    MY_ITU_ZONE,
    
    /// <remarks/>
    MY_LAT,
    
    /// <remarks/>
    MY_LON,
    
    /// <remarks/>
    MY_NAME,
    
    /// <remarks/>
    MY_NAME_INTL,
    
    /// <remarks/>
    MY_POSTAL_CODE,
    
    /// <remarks/>
    MY_POSTAL_CODE_INTL,
    
    /// <remarks/>
    MY_RIG,
    
    /// <remarks/>
    MY_RIG_INTL,
    
    /// <remarks/>
    MY_SIG,
    
    /// <remarks/>
    MY_SIG_INFO,
    
    /// <remarks/>
    MY_SIG_INFO_INTL,
    
    /// <remarks/>
    MY_SIG_INTL,
    
    /// <remarks/>
    MY_SOTA_REF,
    
    /// <remarks/>
    MY_STATE,
    
    /// <remarks/>
    MY_STREET,
    
    /// <remarks/>
    MY_STREET_INTL,
    
    /// <remarks/>
    MY_USACA_COUNTIES,
    
    /// <remarks/>
    MY_VUCC_GRIDS,
    
    /// <remarks/>
    NAME,
    
    /// <remarks/>
    NAME_INTL,
    
    /// <remarks/>
    NOTES,
    
    /// <remarks/>
    NOTES_INTL,
    
    /// <remarks/>
    NR_BURSTS,
    
    /// <remarks/>
    NR_PINGS,
    
    /// <remarks/>
    OPERATOR,
    
    /// <remarks/>
    OWNER_CALLSIGN,
    
    /// <remarks/>
    PFX,
    
    /// <remarks/>
    PRECEDENCE,
    
    /// <remarks/>
    PROP_MODE,
    
    /// <remarks/>
    PUBLIC_KEY,
    
    /// <remarks/>
    QRZCOM_QSO_UPLOAD_DATE,
    
    /// <remarks/>
    QRZCOM_QSO_UPLOAD_STATUS,
    
    /// <remarks/>
    QSLMSG,
    
    /// <remarks/>
    QSLMSG_INTL,
    
    /// <remarks/>
    QSLRDATE,
    
    /// <remarks/>
    QSLSDATE,
    
    /// <remarks/>
    QSL_RCVD,
    
    /// <remarks/>
    QSL_RCVD_VIA,
    
    /// <remarks/>
    QSL_SENT,
    
    /// <remarks/>
    QSL_SENT_VIA,
    
    /// <remarks/>
    QSL_VIA,
    
    /// <remarks/>
    QSO_COMPLETE,
    
    /// <remarks/>
    QSO_DATE,
    
    /// <remarks/>
    QSO_DATE_OFF,
    
    /// <remarks/>
    QSO_RANDOM,
    
    /// <remarks/>
    QTH,
    
    /// <remarks/>
    QTH_INTL,
    
    /// <remarks/>
    REGION,
    
    /// <remarks/>
    RIG,
    
    /// <remarks/>
    RIG_INTL,
    
    /// <remarks/>
    RST_RCVD,
    
    /// <remarks/>
    RST_SENT,
    
    /// <remarks/>
    RX_PWR,
    
    /// <remarks/>
    SAT_MODE,
    
    /// <remarks/>
    SAT_NAME,
    
    /// <remarks/>
    SFI,
    
    /// <remarks/>
    SIG,
    
    /// <remarks/>
    SIG_INFO,
    
    /// <remarks/>
    SIG_INFO_INTL,
    
    /// <remarks/>
    SIG_INTL,
    
    /// <remarks/>
    SILENT_KEY,
    
    /// <remarks/>
    SKCC,
    
    /// <remarks/>
    SOTA_REF,
    
    /// <remarks/>
    SRX,
    
    /// <remarks/>
    SRX_STRING,
    
    /// <remarks/>
    STATE,
    
    /// <remarks/>
    STATION_CALLSIGN,
    
    /// <remarks/>
    STX,
    
    /// <remarks/>
    STX_STRING,
    
    /// <remarks/>
    SUBMODE,
    
    /// <remarks/>
    SWL,
    
    /// <remarks/>
    TEN_TEN,
    
    /// <remarks/>
    TIME_OFF,
    
    /// <remarks/>
    TIME_ON,
    
    /// <remarks/>
    TX_PWR,
    
    /// <remarks/>
    UKSMG,
    
    /// <remarks/>
    USACA_COUNTIES,
    
    /// <remarks/>
    USERDEF,
    
    /// <remarks/>
    VUCC_GRIDS,
    
    /// <remarks/>
    WEB,
}
