//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamRadioLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HamRadioLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Band;LOWERFREQUENTIE;HIGHERFREQUENTIE
        ///2190m;.1357;.1378
        ///630m;.472;.479
        ///560m;.501;.504
        ///160m;1.8;2.0
        ///80m;3.5;4.0
        ///60m;5.06;5.45
        ///40m;7.0;7.3
        ///30m;10.1;10.15
        ///20m;14.0;14.35
        ///17m;18.068;18.168
        ///15m;21.0;21.45
        ///12m;24.890;24.99
        ///10m;28.0;29.7
        ///8m;40;45
        ///6m;50;54
        ///5m;54.000.001;69.9
        ///4m;70;71
        ///2m;144;148
        ///1.25m;222;225
        ///70cm;420;450
        ///33cm;902;928
        ///23cm;1240;1300
        ///13cm;2300;2450
        ///9cm;3300;3500
        ///6cm;5650;5925
        ///3cm;10000;10500
        ///1.25cm;24000;24250
        ///6mm;47000;47200
        ///4mm;75500;81000
        ///2.5mm;119980;120020
        ///2mm;1420 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BandEnumeration {
            get {
                return ResourceManager.GetString("BandEnumeration", resourceCulture);
            }
        }
    }
}
